export * from './AsignacionSupervisorVendedor/AsignacionSupervisorVendedorApi';
export * from './AsignacionClienteVendedor/asignacionClienteVendedorApi';
export * from './Asistencia/asistenciaApi';
export * from './Cliente/clienteApi';
export * from './DireccionCliente/direccionCliente';
export * from './Evidencia/evidenciaApi';
export * from './Ruta/rutaApi';
export * from './SeguimientoVendedor/seguimientoVendedorApi';
export * from './Usuario/usuarioApi';
export * from './Visita/visitaApi';
export * from './Zona/zonaApi';
export * from './Rol/rolApi';
export * from './MarcarLlegadaVisita/marcarLlegadaVisitaApi'
export * from './Reportes/ReporteApi'